(* ::Package:: *)

(* ::Input:: *)
(*Print["Programa que define una matriz cuadrada de orden 3 en la que el elemento que ocupe la posicion (i,j) sea de la forma 2i+5j.Hacer ceros los elementos por debajo de la matriz diagonal principal y calculo del determinante"]*)
(*Print["a11 = ", 2(1)+5(1)]*)
(*Print["a12 = ",2(1)+5(7)]*)
(*Print["a13 = ",2(1)+5(37)]*)
(**)
(*Print["a21 = ",0]*)
(*Print["a22 = ",2(7)+5(7)]*)
(*Print["a23 = ",2(7)+5(37)]*)
(**)
(*Print["a31 = ",0]*)
(*Print["a32 = ",0]*)
(*Print["a33 = ",2(49)+5(49)]*)
(**)
(*matrix//MatrixForm*)
(*\!\(\**)
(*TagBox[*)
(*RowBox[{"(", GridBox[{*)
(*{"7", "37", "187"},*)
(*{"0", "49", "199"},*)
(*{"0", "0", "343"}*)
(*},*)
(*GridBoxAlignment->{"Columns" -> {{Center}}, "ColumnsIndexed" -> {}, "Rows" -> {{Baseline}}, "RowsIndexed" -> {}, "Items" -> {}, "ItemsIndexed" -> {}},*)
(*GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.7]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.4]}, Offset[0.2]}, "RowsIndexed" -> {}, "Items" -> {}, "ItemsIndexed" -> {}}], ")"}],*)
(*Function[BoxForm`e$, MatrixForm[BoxForm`e$]]]\)*)
(*Print["El determinante de la matriz es ",Det[{{7,37,187},{0,49,199},{0,0,343}}]]*)


(* ::Input:: *)
(**)


(* ::Input:: *)
(**)
