(* ::Package:: *)

(* ::Input:: *)
(*(*Ejercicio 7: a) \[DownQuestion]Cuantos numerosprimos hay menores que 10000?*)*)
(**)
(*Print["Hay  ",PrimePi[1000]," Numeros primos Menores que 10000"]*)
(**)
(**)
(*(*b) \[DownQuestion]Cuantos numeros menores que 500 son multiplos de 3,5 y 7 al mismo tiempo?*)*)
(*Print["Multiplos de 3"]*)
(*multiplo3=Table[3n,{n,500 / 3 }]*)
(**)
(*Print["Multiplos de 5"]*)
(*multiplo5=Table[5n,{n,500 / 5 }]*)
(**)
(*Print["Multiplos de 7"]*)
(*multiplo7=Table[7n,{n,500 / 7 }]*)
(**)
(*Print["Multiplos de 3 , 5 y 7 al mismo tiempo"]*)
(*Intersection[multiplo3,multiplo5,multiplo7]*)
(**)
(**)



