(* ::Package:: *)

(* ::Input:: *)
(*Print["Programa que calcula la letra NIF, sabiendo que esta se obtiene a partir del resto de la division del numero del DNI por 23 y que los siguientes pares muestran la relacion de dicho resto con la letra  correspondiente"]*)
(*Print["DNI = ",DNI=976543212]*)
(*LetraNIF=Mod[DNI,23]*)
(*Print["Letra NIF"]*)
(**)
(*If[LetraNIF==1,R]*)
(*If[LetraNIF==2,W]*)
(*If[LetraNIF==3,A]*)
(*If[LetraNIF==4,G]*)
(*If[LetraNIF==5,M]*)
(*If[LetraNIF==6,Y]*)
(*If[LetraNIF==7,F]*)
(*If[LetraNIF==8,P]*)
(*If[LetraNIF==9,D]*)
(*If[LetraNIF==10,X]*)
(*If[LetraNIF==11,B]*)
(*If[LetraNIF==12,N]*)
(*If[LetraNIF==13,J]*)
(*If[LetraNIF==14,Z]*)
(*If[LetraNIF==15,S]*)
(*If[LetraNIF==16,Q]*)
(*If[LetraNIF==17,V]*)
(*If[LetraNIF==18,H]*)
(*If[LetraNIF==19,L]*)
(*If[LetraNIF==20,C]*)
(*If[LetraNIF==21,K]*)
(*If[LetraNIF==22,E]*)
(*If[LetraNIF==0,T]*)



